// Automatically generated by MockGen. DO NOT EDIT!
// Source: cache_monitor.go

package mock_client

import (
	gomock "github.com/innotech/hydra-reverse-proxy/vendors/github.com/innotech/hydra-go-client/vendors/code.google.com/p/gomock/gomock"
)

// Mock of CacheMonitor interface
type MockCacheMonitor struct {
	ctrl		*gomock.Controller
	recorder	*_MockCacheMonitorRecorder
}

// Recorder for MockCacheMonitor (not exported)
type _MockCacheMonitorRecorder struct {
	mock *MockCacheMonitor
}

func NewMockCacheMonitor(ctrl *gomock.Controller) *MockCacheMonitor {
	mock := &MockCacheMonitor{ctrl: ctrl}
	mock.recorder = &_MockCacheMonitorRecorder{mock}
	return mock
}

func (_m *MockCacheMonitor) EXPECT() *_MockCacheMonitorRecorder {
	return _m.recorder
}

func (_m *MockCacheMonitor) Run() {
	_m.ctrl.Call(_m, "Run")
}

func (_mr *_MockCacheMonitorRecorder) Run() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Run")
}
